import json
import os
import uuid
import pandas as pd
from datetime import datetime

path = os.getcwd()
dashboards_json_path = os.path.join(path, 'data', 'visualizations', 'validated_dashboard.json')
_ds_config_path = os.path.join(path, 'configurations.json')
_ssh_dir        = os.path.join(path, 'ssh')


def load_dashboards_from_file():
    try:
        with open(dashboards_json_path, 'r') as f:
            data = json.load(f)
            return data if isinstance(data, list) else [data]
    except (FileNotFoundError, json.JSONDecodeError):
        return []

def save_dashboards_to_file(data):
    with open(dashboards_json_path, 'w') as f:
        json.dump(data, f, indent=2)

def discover_metric_keys():
    """Scan every count across every dashboard for the top-level and filter keys
    that have ever been used, so the editor can suggest keys the user hasn't added yet."""
    top_level_keys = set()
    filter_keys = set()
    for dashboard in load_dashboards_from_file():
        for count in dashboard.get("visualization_types", {}).get("counts", []):
            if not isinstance(count, dict):
                continue
            top_level_keys.update(k for k in count.keys() if k not in ("id", "name", "filters"))
            filters = count.get("filters")
            if isinstance(filters, dict):
                filter_keys.update(filters.keys())
    return {"top_level": sorted(top_level_keys), "filters": sorted(filter_keys)}

def discover_chart_keys():
    """Scan every chart item across every section/dashboard for the top-level keys used,
    and the filter keys used per chart 'type', so suggestions can be tailored to the
    chart type currently being edited."""
    top_level_keys = set()
    by_type = {}
    for dashboard in load_dashboards_from_file():
        sections = dashboard.get("visualization_types", {}).get("charts", {}).get("sections", [])
        for section in sections:
            for item in section.get("items", []):
                if not isinstance(item, dict):
                    continue
                top_level_keys.update(k for k in item.keys() if k not in ("id", "name", "type", "filters"))
                chart_type = item.get("type")
                filters = item.get("filters")
                if chart_type and isinstance(filters, dict):
                    by_type.setdefault(chart_type, set()).update(filters.keys())
    return {
        "top_level": sorted(top_level_keys),
        "by_type": {t: sorted(keys) for t, keys in by_type.items()},
    }

def _coerce_list(value):
    if value in (None, "", []):
        return []
    if isinstance(value, list):
        return [v for v in value if v not in (None, "")]
    return [value]

def _normalize_filter_value(value):
    if isinstance(value, list):
        cleaned = [v for v in value if v not in (None, "")]
        if not cleaned:
            return []
        return cleaned
    if value in (None, ""):
        return ""
    return value

def _safe_json_loads(raw_value, default):
    if raw_value in (None, "", []):
        return default
    if isinstance(raw_value, (dict, list)):
        return raw_value
    try:
        return json.loads(raw_value)
    except (TypeError, json.JSONDecodeError):
        return default

DEFAULT_METRIC_PAYLOAD = {
    "id": "autogenerated as count_xxxxxx",
    "display": "True",
    "name": "",
    "level": "facility",
    "flag": "",
    "display_average": "False",
    "href": "",
    "drill_down": "False",
    "show_trend": "False",
    "group_by": "",
    "custom_sql": "",
    "filters": {
        "measure": "count",
        "unique": "person_id"
    }
}

DEFAULT_CHART_PAYLOAD = {
    "id": "autogenerated as chart_xxxxxx",
    "display": "True",
    "name": "",
    "type": "",
    "level": "facility",
    "filters": {
        "measure": "",
        "unique": "any",
        "unique_column": "person_id",
        "title": ""
    }
}

def _empty_dashboard_structure(report_id, report_name, date_created):
    return {
        "report_id": report_id or f"report_{uuid.uuid4().hex[:8]}",
        "report_name": report_name or "New Dashboard",
        "date_created": date_created or datetime.now().strftime("%Y-%m-%d"),
        "visualization_types": {
            "counts": [],
            "charts": {
                "sections": []
            }
        }
    }

def _find_dashboard_index(dashboards_data, selector_value=None, report_id=None):
    if isinstance(selector_value, int) and 0 <= selector_value < len(dashboards_data):
        return selector_value
    if report_id:
        for idx, dashboard in enumerate(dashboards_data):
            if dashboard.get("report_id") == report_id:
                return idx
    return None

def _ensure_dashboard_for_edit(selector_value, report_id, report_name, date_created):
    dashboards_data = load_dashboards_from_file()
    dashboard_index = _find_dashboard_index(dashboards_data, selector_value, report_id)

    if dashboard_index is None:
        dashboard = _empty_dashboard_structure(report_id, report_name, date_created)
        dashboards_data.append(dashboard)
        dashboard_index = len(dashboards_data) - 1
        save_dashboards_to_file(dashboards_data)
    else:
        dashboard = dashboards_data[dashboard_index]
        dashboard.setdefault("visualization_types", {})
        dashboard["visualization_types"].setdefault("counts", [])
        dashboard["visualization_types"].setdefault("charts", {})
        dashboard["visualization_types"]["charts"].setdefault("sections", [])

    return dashboards_data, dashboards_data[dashboard_index], dashboard_index

def _get_active_viz_types(dashboard, tab_id=None):
    """Return the visualization_types dict the metric/chart editor should read and write —
    the dashboard's own (standard/mnid outlook), or a specific tab's (tab outlook)."""
    if tab_id:
        for tab in dashboard.get("visualization_tabs", []):
            if tab.get("tab_id") == tab_id:
                viz = tab.setdefault("visualization_types", {})
                viz.setdefault("counts", [])
                viz.setdefault("charts", {}).setdefault("sections", [])
                return viz
    viz = dashboard.setdefault("visualization_types", {})
    viz.setdefault("counts", [])
    viz.setdefault("charts", {}).setdefault("sections", [])
    return viz

def _dashboard_tab_options(dashboard):
    return [{"label": t.get("tab_name") or f"Tab {i + 1}", "value": t.get("tab_id")}
            for i, t in enumerate(dashboard.get("visualization_tabs", []))]

def _dashboard_selector_options(dashboards_data):
    return [{"label": f"📋 {d.get('report_name', 'Unnamed')}", "value": i}
            for i, d in enumerate(dashboards_data)] + [
                {"label": "➕ Create New Dashboard", "value": "new"}
            ]

def _load_datasources():
    try:
        with open(_ds_config_path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return []


def _save_datasources(data):
    with open(_ds_config_path, 'w') as f:
        json.dump(data, f, indent=2)


def _list_ssh_keys():
    """Return .pem/.cer/.key filenames from the project ssh/ directory."""
    if not os.path.isdir(_ssh_dir):
        return []
    return sorted(
        f for f in os.listdir(_ssh_dir)
        if f.endswith(('.pem', '.cer', '.key'))
    )


def _load_user_csv(route):
    _users_csv_path        = os.path.join(path, f'data/{route}', 'single_tables', 'users_data.csv')
    if not os.path.exists(_users_csv_path):
        return pd.DataFrame(columns=['User', 'uuid', 'role'])
    df = pd.read_csv(_users_csv_path)
    df = df.dropna(subset=['User']).drop_duplicates(subset=['User'])
    return df

def _load_user_props(route):
    _user_props_path       = os.path.join(path, f'data/{route}', 'dcc_dropdown_json', 'user_properties.json')
    if not os.path.exists(_user_props_path):
        return {"users": []}
    try:
        with open(_user_props_path) as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return {"users": []}

def _save_user_props(data, route):
    _user_props_path       = os.path.join(path, f'data/{route}', 'dcc_dropdown_json', 'user_properties.json')
    os.makedirs(os.path.dirname(_user_props_path), exist_ok=True)
    with open(_user_props_path, 'w') as f:
        json.dump(data, f, indent=2)

def _load_facilities(route):
    _facilities_json_path  = os.path.join(path, f'data/{route}', 'dcc_dropdown_json', 'facilities_dropdowns.json')
    try:
        with open(_facilities_json_path) as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _extract_identifiers(sql: str) -> list[str]:
    """Return word-like tokens from SQL that could be column names."""
    import re as _re
    # Remove string literals and comments first
    sql_clean = _re.sub(r"'[^']*'", " ", sql)
    sql_clean = _re.sub(r'"[^"]*"', " ", sql_clean)
    sql_clean = _re.sub(r"--[^\n]*", " ", sql_clean)
    # SQL keywords to skip
    _KEYWORDS = {
        "select","from","where","and","or","not","in","is","null","like","data",
        "limit","offset","group","by","order","having","join","on","as",
        "distinct","count","sum","avg","min","max","between","case","when",
        "then","else","end","with","inner","left","right","outer","cross",
        "union","all","insert","update","delete","create","drop","cast",
        "timestamp","date","interval","true","false","asc","desc","exists",
    }
    tokens = _re.findall(r"\b[A-Za-z_][A-Za-z0-9_]*\b", sql_clean)
    return [t for t in tokens if t.lower() not in _KEYWORDS]
