"""Configuration registry for dashboards that opt into premium layouts."""

DASHBOARD_PROFILES = {
    "Maternal and Child Health": {
        "layout": "premium",
        "variant": "mnid_light",
        "theme": "premium_mch",
        "brand": "Maternal & Child",
        "kicker": "Strategic Overview",
        "subtitle": (
            "A reusable clinical dashboard shell for maternal, newborn, labour, and postnatal monitoring."
        ),
        "overview_title": "Key maternal and child indicators at a glance",
        "overview_copy": (
            "This layout separates executive KPIs from clinical detail so programme teams, clinicians, "
            "and donor reviewers can assess service coverage, intervention quality, and referral burden quickly."
        ),
        "section_chip_label": "Focus Areas",
        "topbar_pills": [
            {"label": "M-NID view", "tone": "blue"},
            {"label": "Clinical quality", "tone": "green"},
            {"label": "Facility dashboard", "tone": "amber"},
        ],
        "tracker_title": "Priority intervention coverage tracker",
        "tracker_target": 80,
        "indicator_clusters": [
            {
                "title": "Maternal Screening",
                "tone": "blue",
                "metrics": [
                    "ANC Clients Screened for Anemia",
                    "ANC Clients Screened for Infection",
                    "ANC Clients Screened for High BP",
                ],
            },
            {
                "title": "Labour and Delivery",
                "tone": "purple",
                "metrics": [
                    "POCUS With Gestational Age Recorded",
                    "Deliveries With Digital Monitoring",
                    "PPH Treatment Bundle Completed",
                ],
            },
            {
                "title": "Newborn and PNC",
                "tone": "pink",
                "metrics": [
                    "PNC Mothers Within 48 Hours",
                    "Babies Receiving BCG",
                ],
            },
            {
                "title": "Intrapartum and Newborn Interventions",
                "tone": "amber",
                "metrics": [
                    "Antenatal Corticosteroids Given",
                    "Prophylactic Azithromycin Given",
                    "Neonatal Resuscitation Provided",
                    "iKMC Initiated",
                    "Phototherapy Given",
                    "Neonates Not Hypothermic on Admission",
                    "Parenteral Antibiotics for Neonates",
                    "CPAP Support Provided",
                ],
            },
            {
                "title": "Readiness and Quality",
                "tone": "green",
                "metrics": [
                    "HIV Testing Coverage",
                    "Record Completeness",
                    "Data Entered Within 7 Days",
                    "Essential Medicine Availability",
                    "EmONC Competency Assessed",
                    "SSNC Competency Assessed",
                    "CPAP Equipment Available",
                    "Phototherapy Unit Available",
                    "Stockout Tracking Linked",
                    "Referral Completed",
                ],
            },
        ],
        "facility_comparison_metrics": [
            "ANC Clients Screened for Anemia",
            "ANC Clients Screened for High BP",
            "POCUS With Gestational Age Recorded",
            "Deliveries With Digital Monitoring",
            "PPH Treatment Bundle Completed",
            "Antenatal Corticosteroids Given",
            "Neonatal Resuscitation Provided",
            "PNC Mothers Within 48 Hours",
        ],
        "spotlight_metrics": [
            "ANC Clients Screened for Anemia",
            "ANC Clients Screened for High BP",
            "PPH Treatment Bundle Completed",
            "Neonatal Resuscitation Provided",
            "PNC Mothers Within 48 Hours",
        ],
        "supplemental_metrics": [
            # ANC screening
            {
                "name": "ANC Clients Screened for Anemia",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "Anemia screening",
                    "variable4": "obs_value_coded", "value4": "Screened",
                },
            },
            {
                "name": "ANC Clients Screened for Infection",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "Infection screening",
                    "variable4": "obs_value_coded", "value4": "Screened",
                },
            },
            {
                "name": "ANC Clients Screened for High BP",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "High blood pressure screening",
                    "variable4": "obs_value_coded", "value4": "Screened",
                },
            },
            # Labour
            {
                "name": "POCUS With Gestational Age Recorded",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "POCUS completed",
                    "variable4": "obs_value_coded", "value4": "Yes",
                },
            },
            {
                "name": "Deliveries With Digital Monitoring",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "LABOUR AND DELIVERY",
                    "variable3": "concept_name", "value3": "Digital intrapartum monitoring",
                    "variable4": "obs_value_coded", "value4": "Used",
                },
            },
            {
                "name": "PPH Treatment Bundle Completed",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "LABOUR AND DELIVERY",
                    "variable3": "concept_name", "value3": "PPH treatment bundle",
                    "variable4": "obs_value_coded", "value4": "Completed",
                },
            },
            # PNC / newborn
            {
                "name": "PNC Mothers Within 48 Hours",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "Postnatal check period",
                    "variable4": "obs_value_coded",
                    "value4": "Up to 48 hrs or before discharge",
                },
            },
            {
                "name": "Babies Receiving BCG",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "Immunisation given",
                    "variable4": "obs_value_coded", "value4": "BCG",
                },
            },
            # Intrapartum interventions
            {
                "name": "Antenatal Corticosteroids Given",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Antenatal corticosteroids given",
                    "value4": "Yes",
                },
            },
            {
                "name": "Prophylactic Azithromycin Given",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Prophylactic azithromycin given",
                    "value4": "Yes",
                },
            },
            {
                "name": "Neonatal Resuscitation Provided",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Neonatal resuscitation provided",
                    "value4": "Yes",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Neonatal resuscitation provided",
                },
            },
            {
                "name": "iKMC Initiated",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "iKMC initiated",
                    "value4": "Yes",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "iKMC initiated",
                },
            },
            {
                "name": "Phototherapy Given",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Phototherapy given",
                    "value4": "Yes",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Phototherapy given",
                },
            },
            {
                "name": "Neonates Not Hypothermic on Admission",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Thermal status on admission",
                    "value4": "Not hypothermic",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "NEONATAL CARE",
                    "value3": "Thermal status on admission",
                },
            },
            {
                "name": "Record Completeness",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "POSTNATAL CARE",
                    "value3": "Record completeness",
                    "value4": "Complete",
                },
            },
            {
                "name": "Data Entered Within 7 Days",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "POSTNATAL CARE",
                    "value3": "Data entered within 7 days",
                    "value4": "Yes",
                },
            },
            {
                "name": "Essential Medicine Availability",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Essential medicine availability",
                    "value4": "All available",
                },
            },
            {
                "name": "EmONC Competency Assessed",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "EmONC competency assessed",
                    "value4": "Assessed",
                },
            },
            {
                "name": "CPAP Equipment Available",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "CPAP equipment status",
                    "value4": "Available",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "CPAP equipment status",
                },
            },
            {
                "name": "Phototherapy Unit Available",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Phototherapy unit status",
                    "value4": "Available",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Phototherapy unit status",
                },
            },
            # From MNID 
            {
                "name": "HIV Testing Coverage",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "HIV Test",
                    "variable4": "obs_value_coded",
                    "value4": "['Reactive', 'Non-reactive']",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "ANC VISIT",
                    "variable3": "concept_name", "value3": "HIV Test",
                },
            },
            {
                "name": "Parenteral Antibiotics for Neonates",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "NEONATAL CARE",
                    "variable3": "concept_name", "value3": "Parenteral antibiotics given",
                    "variable4": "obs_value_coded", "value4": "Yes",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "NEONATAL CARE",
                    "variable3": "concept_name", "value3": "Parenteral antibiotics given",
                },
            },
            {
                "name": "CPAP Support Provided",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "NEONATAL CARE",
                    "variable3": "concept_name", "value3": "CPAP support",
                    "variable4": "obs_value_coded",
                    "value4": "['Bubble CPAP', 'Nasal oxygen']",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "NEONATAL CARE",
                    "variable3": "concept_name", "value3": "CPAP support",
                },
            },
            {
                "name": "SSNC Competency Assessed",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "SSNC competency assessed",
                    "variable4": "obs_value_coded", "value4": "Assessed",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "SSNC competency assessed",
                },
            },
            {
                "name": "Stockout Tracking Linked",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "Stockout tracking linked",
                    "variable4": "obs_value_coded", "value4": "Linked",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "POSTNATAL CARE",
                    "variable3": "concept_name", "value3": "Stockout tracking linked",
                },
            },
            {
                "name": "Referral Completed",
                "filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "LABOUR AND DELIVERY",
                    "variable3": "concept_name", "value3": "Referral completed",
                    "variable4": "obs_value_coded", "value4": "Yes",
                },
                "benchmark_filters": {
                    "measure": "count", "unique": "person_id",
                    "variable1": "Program", "value1": "MATERNAL AND CHILD HEALTH",
                    "variable2": "Encounter", "value2": "LABOUR AND DELIVERY",
                    "variable3": "concept_name", "value3": "Referral completed",
                },
            },
        ],
        "benchmark_filters": {
            "ANC Clients Screened for Anemia": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Anemia screening",
            },
            "ANC Clients Screened for Infection": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Infection screening",
            },
            "ANC Clients Screened for High BP": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "High blood pressure screening",
            },
            "POCUS With Gestational Age Recorded": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Gestational age recorded",
            },
            "Deliveries With Digital Monitoring": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Digital intrapartum monitoring",
            },
            "PPH Treatment Bundle Completed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "PPH treatment bundle",
            },
            "PNC Mothers Within 48 Hours": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Postnatal check period",
            },
            "Babies Receiving BCG": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Immunisation given",
            },
            "Antenatal Corticosteroids Given": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Antenatal corticosteroids given",
            },
            "Prophylactic Azithromycin Given": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Prophylactic azithromycin given",
            },
            "Neonatal Resuscitation Provided": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "Neonatal resuscitation provided",
            },
            "iKMC Initiated": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "iKMC initiated",
            },
            "Phototherapy Given": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "Phototherapy given",
            },
            "Neonates Not Hypothermic on Admission": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "Thermal status on admission",
            },
            "Record Completeness": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Record completeness",
            },
            "Data Entered Within 7 Days": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Data entered within 7 days",
            },
            "Essential Medicine Availability": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Essential medicine availability",
            },
            "EmONC Competency Assessed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "EmONC competency assessed",
            },
            "HIV Testing Coverage": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "HIV Test",
            },
            "Parenteral Antibiotics for Neonates": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "Parenteral antibiotics given",
            },
            "CPAP Support Provided": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "NEONATAL CARE",
                "value3": "CPAP support",
            },
            "SSNC Competency Assessed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "SSNC competency assessed",
            },
            "Stockout Tracking Linked": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Stockout tracking linked",
            },
            "Referral Completed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Referral completed",
            },
        },
        "indicator_targets": {
            "ANC Clients Screened for Anemia": 80,
            "ANC Clients Screened for Infection": 80,
            "ANC Clients Screened for High BP": 80,
            "POCUS With Gestational Age Recorded": 50,
            "Deliveries With Digital Monitoring": 70,
            "PPH Treatment Bundle Completed": 70,
            "PNC Mothers Within 48 Hours": 80,
            "Babies Receiving BCG": 90,
            "Antenatal Corticosteroids Given": 70,
            "Prophylactic Azithromycin Given": 50,
            "Neonatal Resuscitation Provided": 80,
            "iKMC Initiated": 80,
            "Phototherapy Given": 90,
            "Neonates Not Hypothermic on Admission": 90,
            "Record Completeness": 95,
            "Data Entered Within 7 Days": 90,
            "Essential Medicine Availability": 90,
            "EmONC Competency Assessed": 85,
            "CPAP Equipment Available": 90,
            "Phototherapy Unit Available": 90,
            # MNID
            "HIV Testing Coverage": 95,
            "Parenteral Antibiotics for Neonates": 90,
            "CPAP Support Provided": 80,
            "SSNC Competency Assessed": 80,
            "Stockout Tracking Linked": 80,
            "Referral Completed": 80,
        },
    }
}
