"""Configuration registry for dashboards that opt into premium layouts."""

DASHBOARD_PROFILES = {
    "Maternal and Child Health": {
        "layout": "premium",
        "variant": "mnid_light",
        "theme": "premium_mch",
        "brand": "Maternal & Child",
        "kicker": "Strategic Overview",
        "subtitle": (
            "A reusable clinical dashboard shell for maternal, newborn, labour, and postnatal monitoring."
        ),
        "overview_title": "Key maternal and child indicators at a glance",
        "overview_copy": (
            "This layout separates executive KPIs from clinical detail so programme teams, clinicians, "
            "and donor reviewers can assess service coverage, intervention quality, and referral burden quickly."
        ),
        "section_chip_label": "Focus Areas",
        "topbar_pills": [
            {"label": "M-NID view", "tone": "blue"},
            {"label": "Clinical quality", "tone": "green"},
            {"label": "Facility dashboard", "tone": "amber"},
        ],
        "tracker_title": "Priority intervention coverage tracker",
        "tracker_target": 80,
        "indicator_clusters": [
            {
                "title": "Maternal Screening",
                "tone": "blue",
                "metrics": [
                    "ANC Clients Screened for Anemia",
                    "ANC Clients Screened for Infection",
                    "ANC Clients Screened for High BP",
                ],
            },
            {
                "title": "Labour and Delivery",
                "tone": "purple",
                "metrics": [
                    "POCUS With Gestational Age Recorded",
                    "Deliveries With Digital Monitoring",
                    "PPH Treatment Bundle Completed",
                ],
            },
            {
                "title": "Newborn and PNC",
                "tone": "pink",
                "metrics": [
                    "PNC Mothers Within 48 Hours",
                    "Babies Receiving BCG",
                ],
            },
            {
                "title": "Readiness and Quality",
                "tone": "green",
                "metrics": [
                    "Record Completeness",
                    "Data Entered Within 7 Days",
                    "Essential Medicine Availability",
                    "EmONC Competency Assessed",
                    "CPAP Equipment Available",
                    "Phototherapy Unit Available",
                ],
            },
        ],
        "facility_comparison_metrics": [
            "ANC Clients Screened for Anemia",
            "ANC Clients Screened for High BP",
            "POCUS With Gestational Age Recorded",
            "Deliveries With Digital Monitoring",
            "PPH Treatment Bundle Completed",
            "PNC Mothers Within 48 Hours",
        ],
        "supplemental_metrics": [
            {
                "name": "Record Completeness",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "POSTNATAL CARE",
                    "value3": "Record completeness",
                    "value4": "Complete",
                },
            },
            {
                "name": "Data Entered Within 7 Days",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "POSTNATAL CARE",
                    "value3": "Data entered within 7 days",
                    "value4": "Yes",
                },
            },
            {
                "name": "Essential Medicine Availability",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Essential medicine availability",
                    "value4": "All available",
                },
            },
            {
                "name": "EmONC Competency Assessed",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "EmONC competency assessed",
                    "value4": "Assessed",
                },
            },
            {
                "name": "CPAP Equipment Available",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "CPAP equipment status",
                    "value4": "Available",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "CPAP equipment status",
                },
            },
            {
                "name": "Phototherapy Unit Available",
                "filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "variable4": "obs_value_coded",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Phototherapy unit status",
                    "value4": "Available",
                },
                "benchmark_filters": {
                    "measure": "count",
                    "unique": "person_id",
                    "variable1": "Program",
                    "variable2": "Encounter",
                    "variable3": "concept_name",
                    "value1": "MATERNAL AND CHILD HEALTH",
                    "value2": "LABOUR AND DELIVERY",
                    "value3": "Phototherapy unit status",
                },
            },
        ],
        "benchmark_filters": {
            "ANC Clients Screened for Anemia": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Anemia screening",
            },
            "ANC Clients Screened for Infection": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Infection screening",
            },
            "ANC Clients Screened for High BP": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "High blood pressure screening",
            },
            "POCUS With Gestational Age Recorded": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "ANC VISIT",
                "value3": "Gestational age recorded",
            },
            "Deliveries With Digital Monitoring": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Digital intrapartum monitoring",
            },
            "PPH Treatment Bundle Completed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "PPH treatment bundle",
            },
            "PNC Mothers Within 48 Hours": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Postnatal check period",
            },
            "Babies Receiving BCG": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Immunisation given",
            },
            "Record Completeness": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Record completeness",
            },
            "Data Entered Within 7 Days": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "POSTNATAL CARE",
                "value3": "Data entered within 7 days",
            },
            "Essential Medicine Availability": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "Essential medicine availability",
            },
            "EmONC Competency Assessed": {
                "measure": "count",
                "unique": "person_id",
                "variable1": "Program",
                "variable2": "Encounter",
                "variable3": "concept_name",
                "value1": "MATERNAL AND CHILD HEALTH",
                "value2": "LABOUR AND DELIVERY",
                "value3": "EmONC competency assessed",
            },
        },
        "indicator_targets": {
            "ANC Clients Screened for Anemia": 80,
            "ANC Clients Screened for Infection": 80,
            "ANC Clients Screened for High BP": 80,
            "POCUS With Gestational Age Recorded": 50,
            "Deliveries With Digital Monitoring": 70,
            "PPH Treatment Bundle Completed": 70,
            "PNC Mothers Within 48 Hours": 80,
            "Babies Receiving BCG": 90,
            "Record Completeness": 95,
            "Data Entered Within 7 Days": 90,
            "Essential Medicine Availability": 90,
            "EmONC Competency Assessed": 85,
            "CPAP Equipment Available": 90,
            "Phototherapy Unit Available": 90,
        },
    }
}
