"""Nest360 Newborn & Neonatal indicators."""

def get_nest360_indicators():

    return [
        {
            'id': 'nest360_glucose_monitored_at_admission',
            'label': "Glucose monitored at admission",
            'category': 'Nest360',
            'subcategory': "Vital signs",
            'target': 75,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Glucose monitored at admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Glucose monitored at admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_pulse_oximeter_used_at_admission',
            'label': "Pulse oximeter used at admission",
            'category': 'Nest360',
            'subcategory': "Vital signs",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Pulse oximeter used at admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Pulse oximeter used at admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_temperature_taken_at_admission',
            'label': "Temperature taken at admission",
            'category': 'Nest360',
            'subcategory': "Vital signs",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Temperature taken at admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Temperature taken at admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_weight_taken_at_admission',
            'label': "Weight taken at admission",
            'category': 'Nest360',
            'subcategory': "Vital signs",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Weight taken at admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Weight taken at admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_weight_taken_at_birth',
            'label': "Weight taken at birth",
            'category': 'Nest360',
            'subcategory': "Vital signs",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Weight taken at birth - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Weight taken at birth - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpap_for_eligible_babies',
            'label': "CPAP for eligible babies",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAP for eligible babies - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAP for eligible babies - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpap_for_babies_1000_1499g_prophylactic_for_all',
            'label': "CPAP for babies 1000-1499g (prophylactic for all)",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAP for babies 1000-1499g (prophylactic for all) - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAP for babies 1000-1499g (prophylactic for all) - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpap_1500_1999g_with_symptoms_malawi_nigeria_tanza',
            'label': "CPAP 1500-1999g (with symptoms) [Malawi, Nigeria, Tanzania & Ethiopia]",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAP 1500-1999g (with symptoms) [Malawi, Nigeria, Tanzania & Ethiopia] - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAP 1500-1999g (with symptoms) [Malawi, Nigeria, Tanzania & Ethiopia] - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_time_between_birth_and_cpap_initiation_for_babies_',
            'label': "Time between Birth and CPAP initiation for babies 1000-1999g",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Time between Birth and CPAP initiation for babies 1000-1999g - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Time between Birth and CPAP initiation for babies 1000-1999g - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_time_between_admission_and_cpap_initiation_for_bab',
            'label': "Time between Admission and CPAP initiation for babies 1000-1999g",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Time between Admission and CPAP initiation for babies 1000-1999g - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Time between Admission and CPAP initiation for babies 1000-1999g - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpaps_done_mortality',
            'label': "CPAPs Done & Mortality",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAPs Done & Mortality - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAPs Done & Mortality - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpap_types',
            'label': "CPAP Types",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAP Types - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAP Types - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_cpap_treatment',
            'label': "CPAP Treatment",
            'category': 'Nest360',
            'subcategory': "CPAP",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "CPAP Treatment - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "CPAP Treatment - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_kmc_1000_1999g',
            'label': "KMC 1000-1999g",
            'category': 'Nest360',
            'subcategory': "KMC",
            'target': 75,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "KMC 1000-1999g - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "KMC 1000-1999g - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_kmc_2000_2499g',
            'label': "KMC 2000-2499g",
            'category': 'Nest360',
            'subcategory': "KMC",
            'target': 75,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "KMC 2000-2499g - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "KMC 2000-2499g - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_time_between_birth_to_kmc_initiation_for_babies_10',
            'label': "Time between Birth to KMC initiation for babies 1000-2500g",
            'category': 'Nest360',
            'subcategory': "KMC",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Time between Birth to KMC initiation for babies 1000-2500g - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Time between Birth to KMC initiation for babies 1000-2500g - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_not_hypothermic_after_admission',
            'label': "Not hypothermic after admission*",
            'category': 'Nest360',
            'subcategory': "Hypothermia / warm chain",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic after admission* - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic after admission* - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_not_hypothermic_at_admission',
            'label': "Not hypothermic at admission",
            'category': 'Nest360',
            'subcategory': "Hypothermia / warm chain",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_not_hypothermic_at_admission_inborn',
            'label': "Not hypothermic at admission, inborn",
            'category': 'Nest360',
            'subcategory': "Hypothermia / warm chain",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission, inborn - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission, inborn - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_not_hypothermic_at_admission_outborn',
            'label': "Not hypothermic at admission, outborn",
            'category': 'Nest360',
            'subcategory': "Hypothermia / warm chain",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission, outborn - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Not hypothermic at admission, outborn - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_thermal_status_at_admission',
            'label': "Thermal Status at Admission",
            'category': 'Nest360',
            'subcategory': "Hypothermia / warm chain",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Thermal Status at Admission - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Thermal Status at Admission - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_phototherapy_for_clinical_jaundice_malawi_nigeria_',
            'label': "Phototherapy for clinical jaundice [Malawi, Nigeria, Tanzania & Ethiopia]",
            'category': 'Nest360',
            'subcategory': "Jaundice",
            'target': 90,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Phototherapy for clinical jaundice [Malawi, Nigeria, Tanzania & Ethiopia] - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Phototherapy for clinical jaundice [Malawi, Nigeria, Tanzania & Ethiopia] - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_bilirubin_measurement',
            'label': "Bilirubin Measurement",
            'category': 'Nest360',
            'subcategory': "Jaundice",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Bilirubin Measurement - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Bilirubin Measurement - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_exchange_transfusion',
            'label': "Exchange Transfusion",
            'category': 'Nest360',
            'subcategory': "Jaundice",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Exchange Transfusion - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Exchange Transfusion - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_antibiotics_for_clinical_sepsis',
            'label': "Antibiotics for clinical sepsis",
            'category': 'Nest360',
            'subcategory': "Infection",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Antibiotics for clinical sepsis - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Antibiotics for clinical sepsis - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_culture_done_for_babies_on_antibiotics',
            'label': "Culture done for babies on antibiotics",
            'category': 'Nest360',
            'subcategory': "Infection",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Culture done for babies on antibiotics - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Culture done for babies on antibiotics - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_blood_culture_results_recorded',
            'label': "Blood culture results recorded",
            'category': 'Nest360',
            'subcategory': "Infection",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Blood culture results recorded - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Blood culture results recorded - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_facilities_doing_blood_culture',
            'label': "Facilities doing Blood Culture",
            'category': 'Nest360',
            'subcategory': "Infection",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Facilities doing Blood Culture - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Facilities doing Blood Culture - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_antibiotics_classification',
            'label': "Antibiotics classification",
            'category': 'Nest360',
            'subcategory': "Infection",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Antibiotics classification - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Antibiotics classification - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_positive_blood_culture_rate_among_all_cultures_don',
            'label': "Positive blood culture rate among all cultures done",
            'category': 'Nest360',
            'subcategory': "Blood Culture",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Positive blood culture rate among all cultures done - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Positive blood culture rate among all cultures done - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_percent_probable_contaminants_among_positive_blood',
            'label': "Percent probable contaminants among positive blood cultures",
            'category': 'Nest360',
            'subcategory': "Blood Culture",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Percent probable contaminants among positive blood cultures - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Percent probable contaminants among positive blood cultures - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_distribution_of_microorganisms_identified_in_posit',
            'label': "Distribution of Microorganisms identified in positive blood culture",
            'category': 'Nest360',
            'subcategory': "Blood Culture",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Distribution of Microorganisms identified in positive blood culture - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Distribution of Microorganisms identified in positive blood culture - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_monthly_trend_of_microorganisms_identified_in_posi',
            'label': "Monthly trend of Microorganisms identified in positive blood culture",
            'category': 'Nest360',
            'subcategory': "Blood Culture",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Monthly trend of Microorganisms identified in positive blood culture - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Monthly trend of Microorganisms identified in positive blood culture - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_percentage_of_babies_who_got_breastmilk_on_their_d',
            'label': "Percentage of babies who got breastmilk on their day of birth",
            'category': 'Nest360',
            'subcategory': "Nutrition",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Percentage of babies who got breastmilk on their day of birth - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Percentage of babies who got breastmilk on their day of birth - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_percentage_of_babies_who_were_on_breastmilk_exclus',
            'label': "Percentage of babies who were on breastmilk exclusively at discharge.",
            'category': 'Nest360',
            'subcategory': "Nutrition",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Percentage of babies who were on breastmilk exclusively at discharge. - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Percentage of babies who were on breastmilk exclusively at discharge. - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_percentage_distribution_of_different_feeding_metho',
            'label': "Percentage distribution of different feeding methods for babies at discharge",
            'category': 'Nest360',
            'subcategory': "Nutrition",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Percentage distribution of different feeding methods for babies at discharge - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Percentage distribution of different feeding methods for babies at discharge - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_hypoglycemia',
            'label': "Hypoglycemia",
            'category': 'Nest360',
            'subcategory': "Nutrition",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Hypoglycemia - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Hypoglycemia - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_device_functionality',
            'label': "Device Functionality",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Device Functionality - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Device Functionality - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_consumables',
            'label': "Consumables",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Consumables - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Consumables - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_medicine_availability',
            'label': "Medicine Availability",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Medicine Availability - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Medicine Availability - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_planned_preventive_maintenance_ppm',
            'label': "Planned Preventive Maintenance (PPM)",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Planned Preventive Maintenance (PPM) - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Planned Preventive Maintenance (PPM) - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_device_ratios_for_continuously_used_devices',
            'label': "Device Ratios for continuously used devices",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Device Ratios for continuously used devices - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Device Ratios for continuously used devices - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_device_nurse_ratios_for_intermittently_used_device',
            'label': "Device-Nurse ratios for intermittently used devices",
            'category': 'Nest360',
            'subcategory': "Devices & Supplies",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Device-Nurse ratios for intermittently used devices - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Device-Nurse ratios for intermittently used devices - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_bed_occupancy',
            'label': "Bed Occupancy",
            'category': 'Nest360',
            'subcategory': "Infrastructure",
            'target': 90,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Bed Occupancy - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Bed Occupancy - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_nurse_ratios',
            'label': "Nurse Ratios",
            'category': 'Nest360',
            'subcategory': "Human Resources",
            'target': 4,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Nurse Ratios - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Nurse Ratios - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_trained_nurses',
            'label': "Trained Nurses",
            'category': 'Nest360',
            'subcategory': "Human Resources",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Trained Nurses - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Trained Nurses - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_data_entry_delays',
            'label': "Data Entry Delays",
            'category': 'Nest360',
            'subcategory': "Data Quality",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Data Entry Delays - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Data Entry Delays - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_data_completeness',
            'label': "Data Completeness",
            'category': 'Nest360',
            'subcategory': "Data Quality",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Data Completeness - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Data Completeness - Denominator"},
            'status': 'tracked',
        },
        {
            'id': 'nest360_data_validity',
            'label': "Data Validity",
            'category': 'Nest360',
            'subcategory': "Data Quality",
            'target': 100,
            'numerator_filters': {'variable1': 'indicator_name', 'value1': "Data Validity - Numerator"},
            'denominator_filters': {'variable1': 'indicator_name', 'value1': "Data Validity - Denominator"},
            'status': 'tracked',
        },
    ]